### PR TITLE
give migrations access to the dynamodb client and allow endpoint to be passed in properly

### PR DESCRIPTION
**Pull request by ceceradio**
I thought it was curious that this tool gave access to only the DocumentClient and not a full DynamoDB client, so I added that as a thing for migrations. Also endpoint didn't seem to actually be set up so I pushed that through.

### CODE REVIEW

**Comment by floydspace** [comment]
@ceceradio thank you for your contribution. Could you please tell me more about your use case and what limitations are you facing? so we can together find the best way how to deal with it?

**Comment by ceceradio** [comment]
> @ceceradio thank you for your contribution. Could you please tell me more about your use case and what limitations are you facing? so we can together find the best way how to deal with it? And do not forget hit star if you find the lib useful ;)

For `endpoint` not being an option available, its simply that I need to be able to use this on a local dynamodb instance, and want to define that in .dynamitrc.json

My use case is to have the first migration run on DynamoDB to be setting up the Table(s) and Keys I need. Similar to how in SQL migrations you'd have a `0001_initial.up.sql` to create your tables. It doesn't seem to be possible to create tables with the DocumentClient. It seems like that's a higher level client specifically for accessing items in DynamoDB. So I added some code to pass a DynamoDB client as a second arg to the migrations.

**Comment by floydspace** [comment]
> For `endpoint` not being an option available, its simply that I need to be able to use this on a local dynamodb instance, and want to define that in .dynamitrc.json

makes sense to me. indeed it is not passed to the client. The only I would avoid renaming the property

> My use case is to have the first migration run on DynamoDB to be setting up the Table(s) and Keys I need.

you always can just require `aws-sdk` and import DynamoDB directly in the migration file, and do whatever you'd like. the only problem I see here, that you'll have to duplicate all the aws configuration.  so In this case I would suggest passing `options` as a second argument to the migration callback (`params: [dynamodb, options]`) instead of creating dynamodb instance which is useless for the migrator itself

**Review by floydspace — APPROVED** [review]
@ceceradio thank you 👍

**Comment by ceceradio** [comment]
you were a little fast on the merge @floydspace ! I had to fix a configuration I found while I was testing this out, my bad. Turns out the reason I renamed `endpointUrl` to `endpoint` was because thats the name of the property required for `new DocumentClient()`.  Want me to open another PR or what?

**Comment by floydspace** [comment]
> you were a little fast on the merge @floydspace ! I had to fix a configuration I found while I was testing this out, my bad. Turns out the reason I renamed `endpointUrl` to `endpoint` was because thats the name of the property required for `new DocumentClient()`. Want me to open another PR or what?

sorry it looked okay to me, I merged. yes please open a new PR, if you not sure save it as draft. and please follow conventional commits, so semantic release knows which version to use on delivery

**Pull request merged**
